# Generated by Django 5.1.15 on 2026-02-03 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was soft-deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Banner title (for admin reference only)",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Banner image (recommended: 1920x600 for hero)",
                        upload_to="banners/",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Click destination URL (optional)",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home_hero", "Homepage Hero"),
                            ("home_secondary", "Homepage Secondary"),
                            ("sidebar", "Sidebar"),
                            ("footer", "Footer"),
                        ],
                        db_index=True,
                        default="home_hero",
                        help_text="Where to display this banner",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active banners are eligible for display",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start displaying from this date/time (optional)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stop displaying after this date/time (optional)",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["position", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["position", "is_active", "sort_order"],
                        name="cms_banner_positio_9031bf_idx",
                    ),
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="cms_banner_is_acti_6a6e72_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique setting identifier (e.g., 'site_name')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Setting value (format depends on value_type)",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Type of value stored",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("shop", "Shop"),
                            ("seo", "SEO"),
                            ("social", "Social Media"),
                            ("email", "Email"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="general",
                        help_text="Settings group for organization",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of this setting",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
                "ordering": ["group", "key"],
                "indexes": [
                    models.Index(fields=["key"], name="cms_siteset_key_2a387f_idx"),
                    models.Index(fields=["group"], name="cms_siteset_group_995d86_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of person contacting", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for reply", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number (optional)", max_length=20
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Subject of inquiry", max_length=300),
                ),
                ("message", models.TextField(help_text="Message content")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether admin has read this message",
                    ),
                ),
                (
                    "is_replied",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether admin has replied to this message",
                    ),
                ),
                (
                    "reply_content",
                    models.TextField(
                        blank=True, help_text="Admin's reply to the inquiry"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, help_text="When reply was sent", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of submitter", null=True
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who replied",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="cms_contact_created_731af4_idx"
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="cms_contact_is_read_163178_idx",
                    ),
                    models.Index(
                        fields=["is_replied", "-created_at"],
                        name="cms_contact_is_repl_be6e87_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was soft-deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title displayed in navigation and header",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title (auto-generated)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Page content (supports rich text/HTML)"
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("about", "About Us"),
                            ("contact", "Contact"),
                            ("faq", "FAQ"),
                        ],
                        default="default",
                        help_text="Template to use for rendering this page",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta title (defaults to page title)",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="SEO meta description", max_length=300
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent page for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["sort_order", "title"],
                "indexes": [
                    models.Index(fields=["slug"], name="cms_page_slug_f9a361_idx"),
                    models.Index(
                        fields=["status", "is_deleted"],
                        name="cms_page_status_ee7ced_idx",
                    ),
                    models.Index(
                        fields=["parent", "sort_order"],
                        name="cms_page_parent__fb727d_idx",
                    ),
                ],
            },
        ),
    ]
