# Generated by Django 5.1.15 on 2026-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="reply_content",
            field=models.TextField(
                blank=True, help_text="Admin's reply to the inquiry", null=True
            ),
        ),
    ]
