# Generated by Django 5.1.15 on 2026-02-03 08:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Optional username. Email is used for authentication.",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for API responses.",
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address used for login and communication.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Bangladeshi phone number (e.g., 01712345678).",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Bangladeshi phone number (11 digits starting with 01).",
                                regex="^01[0-9]{9}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Block user from accessing the platform.",
                        verbose_name="Is Blocked",
                    ),
                ),
                (
                    "block_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for blocking this user (internal use).",
                        verbose_name="Block Reason",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has verified their email address.",
                        verbose_name="Email Verified",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of completed orders.",
                        verbose_name="Total Orders",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount spent on all orders.",
                        max_digits=12,
                        verbose_name="Total Spent",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this user (visible only to staff).",
                        verbose_name="Admin Notes",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Custom label (e.g., 'Home', 'Office').",
                        max_length=50,
                        verbose_name="Label",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Full name of person receiving deliveries.",
                        max_length=255,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone number for deliveries.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Bangladeshi phone number (11 digits starting with 01).",
                                regex="^01[0-9]{9}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        help_text="Street address, building name, house number.",
                        max_length=255,
                        verbose_name="Address Line 1",
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, floor, etc. (optional).",
                        max_length=255,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        help_text="City name (e.g., Dhaka, Chittagong).",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        db_index=True,
                        help_text="Area/district within city (e.g., Gulshan, Dhanmondi).",
                        max_length=100,
                        verbose_name="Area",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal/ZIP code (optional).",
                        max_length=10,
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Use this as default shipping address.",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this address.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_user_phone_9474e8_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_staff", "is_active"], name="users_user_is_staf_5f907d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_blocked"], name="users_user_is_bloc_7849bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "is_default"], name="users_custo_user_id_8e14d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["city", "area"], name="users_custo_city_0faa93_idx"
            ),
        ),
    ]
