# Generated by Django 5.1.15 on 2026-02-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was soft-deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum cart value to apply coupon",
                        max_digits=10,
                    ),
                ),
                (
                    "maximum_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount for percentage coupons",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total times coupon can be used (blank = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-user usage limit (blank = unlimited)",
                        null=True,
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=False,
                        help_text="Only for customers with no previous orders",
                    ),
                ),
                (
                    "applicable_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of category IDs (empty = all categories)",
                    ),
                ),
                (
                    "applicable_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of product IDs (empty = all products)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "db_table": "orders_coupon",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="orders_coup_code_ca5871_idx"),
                    models.Index(
                        fields=["is_active", "valid_from", "valid_to"],
                        name="orders_coup_is_acti_f359f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Email or phone for guest users",
                        max_length=255,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="orders.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Usage",
                "verbose_name_plural": "Coupon Usages",
                "db_table": "orders_coupon_usage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["coupon", "user"], name="orders_coup_coupon__bc4e0f_idx"
                    ),
                    models.Index(
                        fields=["coupon", "guest_identifier"],
                        name="orders_coup_coupon__905eae_idx",
                    ),
                ],
            },
        ),
    ]
