# Generated by Django 5.1.15 on 2026-02-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the attribute (e.g., 'Size', 'Color').",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique machine-readable code (e.g., 'size', 'color', 'ram').",
                        max_length=100,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("select", "Select (Single Choice)"),
                            ("multiselect", "Multi-Select"),
                            ("boolean", "Boolean (Yes/No)"),
                            ("date", "Date"),
                            ("color", "Color"),
                        ],
                        default="text",
                        help_text="Type of input field for this attribute.",
                        max_length=20,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for select/multiselect choices and validation rules.",
                        verbose_name="Options",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this attribute must have a value.",
                        verbose_name="Is Required",
                    ),
                ),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether customers can filter products by this attribute.",
                        verbose_name="Is Filterable",
                    ),
                ),
                (
                    "is_variant",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If True, this attribute creates product variants (separate SKUs).",
                        verbose_name="Is Variant Attribute",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to display this attribute on product pages.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in forms and lists.",
                        verbose_name="Sort Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this product type (e.g., 'Clothing', 'Electronics').",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name.",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this product type and what it's used for.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this product type is active and can be used.",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was soft-deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name. Auto-generated if left blank.",
                        max_length=255,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for search engines. Recommended: 50-60 characters.",
                        max_length=70,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description for search results. Recommended: 150-160 characters.",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower numbers appear first.",
                        verbose_name="Sort Order",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name.", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Category description for SEO and display.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image or icon.",
                        null=True,
                        upload_to="categories/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("hidden", "Hidden")],
                        db_index=True,
                        default="active",
                        help_text="Category visibility status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "product_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of products in this category (cached).",
                        verbose_name="Product Count",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (leave blank for root categories).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["parent", "status"],
                        name="products_ca_parent__70e571_idx",
                    ),
                    models.Index(
                        fields=["status", "sort_order"],
                        name="products_ca_status_f83421_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductTypeAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for this attribute.",
                        verbose_name="Sort Order",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_type_attributes",
                        to="products.attribute",
                        verbose_name="Attribute",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_type_attributes",
                        to="products.producttype",
                        verbose_name="Product Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type Attribute",
                "verbose_name_plural": "Product Type Attributes",
                "ordering": ["product_type", "sort_order"],
                "unique_together": {("product_type", "attribute")},
            },
        ),
    ]
