# Generated by Django 5.1.15 on 2026-02-03 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_productattributevalue_productvariant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("sold", "Sold (Order)"),
                            ("restocked", "Restocked"),
                            ("adjustment", "Manual Adjustment"),
                            ("return", "Customer Return"),
                            ("damaged", "Damaged/Lost"),
                            ("reserved", "Reserved (Pending Order)"),
                            ("released", "Released (Cancelled Order)"),
                        ],
                        db_index=True,
                        help_text="Type of inventory change",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Change in quantity (positive=increase, negative=decrease)"
                    ),
                ),
                (
                    "quantity_before",
                    models.IntegerField(
                        help_text="Stock before change",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_after",
                    models.IntegerField(
                        help_text="Stock after change",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference ID (order number, PO number, etc.)",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional context")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change (null for system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Variant whose stock changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Log",
                "verbose_name_plural": "Inventory Logs",
                "db_table": "products_inventorylog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "-created_at"],
                        name="products_in_variant_836a5a_idx",
                    ),
                    models.Index(
                        fields=["change_type", "-created_at"],
                        name="products_in_change__785e4e_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="products_in_referen_cfd1d1_idx"
                    ),
                ],
            },
        ),
    ]
